spring:
  application:
    name: feign
  jackson:
    serialization:
      indent_output: true
endpoints:
    health:
      sensitive: false
server:
  port: ${PORT:8889}




eureka:

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'


